# Generated by Django 6.0 on 2025-12-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Scenario', max_length=100)),
                ('initial_balance', models.FloatField()),
                ('mean_return', models.FloatField()),
                ('volatility', models.FloatField()),
                ('annual_withdrawal', models.FloatField()),
                ('inflation', models.FloatField()),
                ('years', models.IntegerField()),
                ('n_sims', models.IntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
